export const suspeitos = [
  {
    name: "advogado",
    img: require("../assets/images/susp_advogado.webp"),
    imgPb: require("../assets/images/susp_advogado_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
  },
  {
    name: "chef",
    img: require("../assets/images/susp_chef.webp"),
    imgPb: require("../assets/images/susp_chef_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
  },
  {
    name: "coveiro",
    img: require("../assets/images/susp_coveiro.webp"),
    imgPb: require("../assets/images/susp_coveiro_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
  },
  {
    name: "dancarina",
    img: require("../assets/images/susp_dancarina.webp"),
    imgPb: require("../assets/images/susp_dancarina_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 4,
  },
  {
    name: "florista",
    img: require("../assets/images/susp_florista.webp"),
    imgPb: require("../assets/images/susp_florista_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 5,
  },
  {
    name: "medica",
    img: require("../assets/images/susp_medica.webp"),
    imgPb: require("../assets/images/susp_medica_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 6,
  },
  {
    name: "mordomo",
    img: require("../assets/images/susp_mordomo.webp"),
    imgPb: require("../assets/images/susp_mordomo_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 7,
  },
  {
    name: "sargento",
    img: require("../assets/images/susp_sargento.webp"),
    imgPb: require("../assets/images/susp_sargento_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 8,
  },
];
export const armas = [
  {
    name: "espingarda",
    img: require("../assets/images/arma_espingarda.webp"),
    imgPb: require("../assets/images/arma_espingarda_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
  },
  {
    name: "faca",
    img: require("../assets/images/arma_faca.webp"),
    imgPb: require("../assets/images/arma_faca_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
  },
  {
    name: "pa",
    img: require("../assets/images/arma_pa.webp"),
    imgPb: require("../assets/images/arma_pa_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
  },
  {
    name: "pedecabra",
    img: require("../assets/images/arma_pedecabra.webp"),
    imgPb: require("../assets/images/arma_pedecabra_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 4,
  },
  {
    name: "quimica",
    img: require("../assets/images/arma_quimica.webp"),
    imgPb: require("../assets/images/arma_quimica_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 5,
  },
  {
    name: "socoingles",
    img: require("../assets/images/arma_socoingles.webp"),
    imgPb: require("../assets/images/arma_socoingles_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 6,
  },
  {
    name: "tesoura",
    img: require("../assets/images/arma_tesoura.webp"),
    imgPb: require("../assets/images/arma_tesoura_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 7,
  },
  {
    name: "veneno",
    img: require("../assets/images/arma_veneno.webp"),
    imgPb: require("../assets/images/arma_veneno_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 8,
  },
];

export const locais = [
  {
    name: "banco",
    img: require("../assets/images/local_banco.webp"),
    imgPb: require("../assets/images/local_banco_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
  },
  {
    name: "boate",
    img: require("../assets/images/local_boate.webp"),
    imgPb: require("../assets/images/local_boate_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
  },
  {
    name: "cemiterio",
    img: require("../assets/images/local_cemiterio.webp"),
    imgPb: require("../assets/images/local_cemiterio_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
  },
  {
    name: "estacao",
    img: require("../assets/images/local_estacao.webp"),
    imgPb: require("../assets/images/local_estacao_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 4,
  },
  {
    name: "floricultura",
    img: require("../assets/images/local_floricultura.webp"),
    imgPb: require("../assets/images/local_floricultura_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 5,
  },
  {
    name: "hospital",
    img: require("../assets/images/local_hospital.webp"),
    imgPb: require("../assets/images/local_hospital_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 6,
  },
  {
    name: "hotel",
    img: require("../assets/images/local_hotel.webp"),
    imgPb: require("../assets/images/local_hotel_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 7,
  },
  {
    name: "mansao",
    img: require("../assets/images/local_mansao.webp"),
    imgPb: require("../assets/images/local_mansao_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 8,
  },
  {
    name: "praca",
    img: require("../assets/images/local_praca.webp"),
    imgPb: require("../assets/images/local_praca_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 9,
  },
  {
    name: "prefeitura",
    img: require("../assets/images/local_prefeitura.webp"),
    imgPb: require("../assets/images/local_prefeitura_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 10,
  },
  {
    name: "restaurante",
    img: require("../assets/images/local_restaurante.webp"),
    imgPb: require("../assets/images/local_restaurante_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 11,
  },
];

export let guilties: any[] = [];
