export type CardList = {
  name: string;
  img: any;
  imgPb: any;
  pressed: boolean;
  longPressed: boolean;
  checked: boolean;
  cleared: boolean;
  question: boolean;
  id: number;
  type: "suspeitos" | "armas" | "locais" | "capas";
};

export const suspeitos: CardList[] = [
  {
    name: "sargento",
    img: require("../assets/images/susp_sargento.webp"),
    imgPb: require("../assets/images/susp_sargento_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 8,
    type: "suspeitos",
  },
  {
    name: "florista",
    img: require("../assets/images/susp_florista.webp"),
    imgPb: require("../assets/images/susp_florista_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 5,
    type: "suspeitos",
  },
  {
    name: "chef",
    img: require("../assets/images/susp_chef.webp"),
    imgPb: require("../assets/images/susp_chef_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
    type: "suspeitos",
  },
  {
    name: "mordomo",
    img: require("../assets/images/susp_mordomo.webp"),
    imgPb: require("../assets/images/susp_mordomo_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 7,
    type: "suspeitos",
  },
  {
    name: "medica",
    img: require("../assets/images/susp_medica.webp"),
    imgPb: require("../assets/images/susp_medica_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 6,
    type: "suspeitos",
  },
  {
    name: "dancarina",
    img: require("../assets/images/susp_dancarina.webp"),
    imgPb: require("../assets/images/susp_dancarina_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 4,
    type: "suspeitos",
  },
  {
    name: "coveiro",
    img: require("../assets/images/susp_coveiro.webp"),
    imgPb: require("../assets/images/susp_coveiro_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
    type: "suspeitos",
  },

  {
    name: "advogado",
    img: require("../assets/images/susp_advogado.webp"),
    imgPb: require("../assets/images/susp_advogado_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
    type: "suspeitos",
  },
];

export const armas: CardList[] = [
  {
    name: "espingarda",
    img: require("../assets/images/arma_espingarda.webp"),
    imgPb: require("../assets/images/arma_espingarda_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
    type: "armas",
  },
  {
    name: "pa",
    img: require("../assets/images/arma_pa.webp"),
    imgPb: require("../assets/images/arma_pa_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
    type: "armas",
  },
  {
    name: "pedecabra",
    img: require("../assets/images/arma_pedecabra.webp"),
    imgPb: require("../assets/images/arma_pedecabra_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 4,
    type: "armas",
  },
  {
    name: "tesoura",
    img: require("../assets/images/arma_tesoura.webp"),
    imgPb: require("../assets/images/arma_tesoura_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 7,
    type: "armas",
  },
  {
    name: "quimica",
    img: require("../assets/images/arma_quimica.webp"),
    imgPb: require("../assets/images/arma_quimica_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 5,
    type: "armas",
  },
  {
    name: "veneno",
    img: require("../assets/images/arma_veneno.webp"),
    imgPb: require("../assets/images/arma_veneno_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 8,
    type: "armas",
  },
  {
    name: "socoingles",
    img: require("../assets/images/arma_socoingles.webp"),
    imgPb: require("../assets/images/arma_socoingles_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 6,
    type: "armas",
  },
  {
    name: "faca",
    img: require("../assets/images/arma_faca.webp"),
    imgPb: require("../assets/images/arma_faca_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
    type: "armas",
  },
];

export const locais: CardList[] = [
  {
    name: "prefeitura",
    img: require("../assets/images/local_prefeitura.webp"),
    imgPb: require("../assets/images/local_prefeitura_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 10,
    type: "locais",
  },
  {
    name: "restaurante",
    img: require("../assets/images/local_restaurante.webp"),
    imgPb: require("../assets/images/local_restaurante_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 11,
    type: "locais",
  },
  {
    name: "floricultura",
    img: require("../assets/images/local_floricultura.webp"),
    imgPb: require("../assets/images/local_floricultura_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 5,
    type: "locais",
  },
  {
    name: "hospital",
    img: require("../assets/images/local_hospital.webp"),
    imgPb: require("../assets/images/local_hospital_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 6,
    type: "locais",
  },
  {
    name: "boate",
    img: require("../assets/images/local_boate.webp"),
    imgPb: require("../assets/images/local_boate_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
    type: "locais",
  },
  {
    name: "mansao",
    img: require("../assets/images/local_mansao.webp"),
    imgPb: require("../assets/images/local_mansao_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 8,
    type: "locais",
  },
  {
    name: "cemiterio",
    img: require("../assets/images/local_cemiterio.webp"),
    imgPb: require("../assets/images/local_cemiterio_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
    type: "locais",
  },
  {
    name: "praca",
    img: require("../assets/images/local_praca.webp"),
    imgPb: require("../assets/images/local_praca_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 9,
    type: "locais",
  },
  {
    name: "hotel",
    img: require("../assets/images/local_hotel.webp"),
    imgPb: require("../assets/images/local_hotel_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 7,
    type: "locais",
  },
  {
    name: "banco",
    img: require("../assets/images/local_banco.webp"),
    imgPb: require("../assets/images/local_banco_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
    type: "locais",
  },
  {
    name: "estacao",
    img: require("../assets/images/local_estacao.webp"),
    imgPb: require("../assets/images/local_estacao_pb.webp"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 4,
    type: "locais",
  },
];

export const capas: CardList[] = [
  {
    name: "capa suspeitos",
    img: require("../assets/images/capa_cartas_suspeitos.png"),
    imgPb: require("../assets/images/capa_cartas_suspeitos.png"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 1,
    type: "capas",
  },
  {
    name: "capa armas",
    img: require("../assets/images/capa_cartas_armas.png"),
    imgPb: require("../assets/images/capa_cartas_armas.png"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 2,
    type: "capas",
  },
  {
    name: "capa locais",
    img: require("../assets/images/capa_cartas_locais.png"),
    imgPb: require("../assets/images/capa_cartas_locais.png"),
    pressed: false,
    longPressed: false,
    checked: false,
    cleared: false,
    question: false,
    id: 3,
    type: "capas",
  },
];
